# Generated by Django 4.1.13 on 2026-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
